from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

btn_count = KeyboardButton('Выбор функций')
btn_subs = KeyboardButton('Оформить подписку')
btn_back = KeyboardButton('Главная')
btn_continue_subs = KeyboardButton('Продлить подписку')

btn_model_car = KeyboardButton('Выборка по модели')
btn_most_cost = KeyboardButton('Выборка по цене')

cat_hood = KeyboardButton('Капот')
cat_fender = KeyboardButton('Крыло')
cat_headlights = KeyboardButton('Фара')
cat_glasses = KeyboardButton('Стекла')
cat_bumper = KeyboardButton('Бампер')
cat_engine = KeyboardButton('Двигатель')
cat_doors = KeyboardButton('Двери')
cat_srs = KeyboardButton('SRS')
cat_bag = KeyboardButton('Багажник')
cat_all = KeyboardButton('Все позиции')

mark_subaru = KeyboardButton('Subaru')
mark_toyota = KeyboardButton('Toyota')
mark_suzuki = KeyboardButton('Suzuki')
mark_nissan = KeyboardButton('Nissan')
mark_mitsubishi = KeyboardButton('Mitsubishi')
mark_mazda = KeyboardButton('Mazda')
mark_honda = KeyboardButton('Honda')
mark_all = KeyboardButton('Максимум из всех')

start_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_count)
subs_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_subs, btn_back)
continue_subs_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_continue_subs, btn_back)
activate_program = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_model_car, btn_most_cost, btn_back)
input_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_count, btn_back)
category_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(cat_hood, cat_fender, cat_headlights, cat_glasses, cat_bumper, cat_doors, cat_bag, cat_srs, cat_engine, cat_all, btn_back)
btn_marks_category = ReplyKeyboardMarkup(resize_keyboard=True).add(mark_subaru, mark_toyota, mark_suzuki, mark_nissan, mark_mitsubishi, mark_mazda, mark_honda, mark_all, btn_back)