from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

btn_count = KeyboardButton('Выбор функций')
btn_subs = KeyboardButton('Оформить подписку')
btn_back = KeyboardButton('Главная')
btn_continue_subs = KeyboardButton('Продлить подписку')
btn_model_car = KeyboardButton('Выборка по модели')
cat_hood = KeyboardButton('Капот')
cat_fender = KeyboardButton('Крыло')
cat_headlights = KeyboardButton('Фара')
cat_glasses = KeyboardButton('Стекла')
cat_bumper = KeyboardButton('Бампер')
cat_engine = KeyboardButton('Двигатель')
start_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_count)
subs_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_subs, btn_back)
continue_subs_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_continue_subs, btn_back)
activate_program = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_model_car, btn_back)
input_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_count, btn_back)
category_btn = ReplyKeyboardMarkup(resize_keyboard=True).add(cat_hood, cat_fender, cat_headlights, cat_glasses, cat_bumper, cat_engine, btn_back)